# 1-6. 파이썬으로 계산하기

In [1]:
# Array creation

import numpy as np

In [2]:
test_array = np.array([1,4,5,8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [4]:
test_array = np.array([1,4,5,8], 'float32')
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float32

-> 데이터 메모리 영역 공간을 32로

In [5]:
test_array = np.array([1,4,5,'8'], float)
print(test_array)
print(type(test_array[3])) # float type으로 자동 형변환
print(test_array.dtype) # array 전체의 데이터 type 반환
print(test_array.shape) # array의 shape을 반환

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


-> (4,) tuple type으로 반환

In [6]:
test_array = np.array([1,4,5,"8"], float)
test_array

array([1., 4., 5., 8.])

In [7]:
type(test_array[3])

numpy.float64

In [8]:
test_array.dtype

dtype('float64')

In [9]:
test_array.shape

(4,)

In [10]:
# array shape (vector)

test_array = np.array([1,4,5,"8"], float)
test_array

array([1., 4., 5., 8.])

In [11]:
# array shape (matrix)

matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [13]:
# array shape (3rd order tensor)

tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]

np.array(tensor, int).shape

(4, 3, 4)

Array shape - ndim & size

In [14]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]

print(np.array(tensor, int).ndim)
print(np.array(tensor, int).size)

3
48


Array dtype

- Ndarray의 single element가 가지는 data type

In [15]:
np.array([[1,2,3], [4.5,5,6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.array([[1,2,3],[4.5,'5','6']], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

Array nbytes

ndarray object의 메모리 크기를 반환함

In [19]:
np.array([[1,2,3],[4.5,'5','6']], dtype=np.float32).nbytes

24

-> 32bits = 4bytes -> 6*4bytes = 24

In [20]:
np.array([[1,2,3],[4.5,'5','6']], dtype=np.int8).nbytes

6

-> 8bits = 1bytes -> 6*1bytes = 8

In [21]:
np.array([[1,2,3],[4.5,'5','6']], dtype= np.float64).nbytes

48

-> 64bits = 8bytes -> 6*8bytes = 48

## **`Handling shape`**

In [22]:
# reshape

test_matrix = [[1,2,3,4],[1,2,4,8]]
np.array(test_matrix).shape

(2, 4)

In [23]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 4, 8])

In [24]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [25]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [26]:
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [27]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [4, 8]]])

In [28]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

`flatten`

In [30]:
test_matrix= [[[1,2,3,4],[1,2,5,7]], [[1,2,3,4],[1,2,5,7]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 7, 1, 2, 3, 4, 1, 2, 5, 7])

## **`Indexing & slicing`**

In [31]:
# indexing

a = np.array([[1,2,3],[4.5,5,6]],int)

print(a)
print(a[0,0])
print(a[0][0])

a[0,0]= 12 # matrix 0,0에 12 할당
print(a)
a[0][0] = 5 # matrix 0,0에 12 할당
print(a)

[[1 2 3]
 [4 5 6]]
1
1
[[12  2  3]
 [ 4  5  6]]
[[5 2 3]
 [4 5 6]]


In [32]:
test_example = np.array([[1,2,3],[4.5,5,6]],int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
test_example[0][0]

1

In [34]:
test_example[0,0]

1

In [37]:
# slicing

a = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)

print(a[:,2:]) # 전체 row의 2열 이상
print(a[1,1:3]) # 1 row의 1열~2열
print(a[1:3]) # 1 row ~ 2row의 전체

[[ 3  4  5]
 [ 8  9 10]]
[7 8]
[[ 6  7  8  9 10]]


In [39]:
test_example = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]],int)

test_example[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

## **`creation function`**